CREATE TABLE IF NOT EXISTS pendidikan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tahun_ajaran INT NOT NULL DEFAULT 0,
    semester VARCHAR(10) NOT NULL DEFAULT 'GANJIL',
    mata_kuliah VARCHAR(255),
    sks INT NOT NULL DEFAULT 0,
    kelas VARCHAR(10) NOT NULL DEFAULT 'A',
    status VARCHAR(15) NOT NULL DEFAULT 'BELUM_UPLOAD',
    file_path VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);